# robot_cfg:
#   name: h1_inspire_mirror

#   is_ACE: true

#   mode: normal

#   pos_scale: 1.5
#   roll_scale: 2.0
#   pitch_scale: 2.0
#   yaw_scale: 2.0

#   roll_limit: [-3, 3]
#   pitch_limit: [-3, 3]
#   yaw_limit: [-3, 3]

#   roll_offset: 20

#   right_wrist:
#     right_wrist_init_rot: [[ 0,  0,  -1], [ -1,  0,  0], [ 0,  1,  0]]
#     right_wrist_init_pos: [0.320, 0.1, 0.145]
#     right_center: [0.33, 0.05, 0.45]
#     right_radius: 0.5

#   right_agent:
#     dynamixel_cfg:
#       #port: /dev/serial/by-id/usb-FTDI_USB__-__Serial_Converter_FT8ISG7I-if00-port0#例子
#       port: /dev/serial/by-id/usb-FTDI_USB__-__Serial_Converter_FT9HDF61-if00-port0
#       urdf: right_arm/robot.urdf
#       ee_link_name: ee_c
#     hand_cfg:
#       cam_num: 2
#       hand_type: Right


# robot_cfg:
#   name: franka_gripper

#   is_ACE: true

#   mode: normal

#   pos_scale: 1.5
#   roll_scale: 2.0
#   pitch_scale: 2.0
#   yaw_scale: 2.0

#   roll_limit: [-3, 3]
#   pitch_limit: [-3, 3]
#   yaw_limit: [-3, 3]


#   roll_offset: 20

#   right_wrist:
#     right_wrist_init_rot: [[ 0,  0,  -1], [ -1,  0,  0], [ 0,  1,  0]]
#     # right_wrist_init_pos: [0.4, 0, 0.5] 
#     # right_center: [0.5, 0, 0.5]
#     right_wrist_init_pos: [0.5, 0.3, 0.3]
#     right_center: [0.5, 0.3, 0.3]
#     right_radius: 0.3
#     # right_wrist_init_pos: [0.383, 0.167, 0.795] #0.795
#     # right_center: [0.383, 0.167, 0.795] 
#     # right_radius: 0.3

#   right_agent:
#     dynamixel_cfg:
#       #port: /dev/serial/by-id/usb-FTDI_USB__-__Serial_Converter_FT8ISG7I-if00-port0#例子
#       port: /dev/serial/by-id/usb-FTDI_USB__-__Serial_Converter_FT9HDF61-if00-port0
#       urdf: right_arm/robot.urdf
#       ee_link_name: ee_c
#     hand_cfg:
#       cam_num: 5
#       hand_type: Right



robot_cfg:
  name: franka_gripper

  is_ACE: true

  mode: normal

  pos_scale: 0.9
  roll_scale: 2.0
  pitch_scale: 2.0
  yaw_scale: 2.0

  roll_limit: [-3, 3]
  pitch_limit: [-3, 3]
  yaw_limit: [-3, 3]


  roll_offset: 20

  # left_wrist:
  #   left_wrist_init_rot: [[ 0,  0, -1], [ 1,  0,  0], [ 0,  -1,  0]] 
  #   left_wrist_init_pos: [-0.5, 0.3, 0.3]
  #   left_center: [-0.5, 0.3, 0.3]
  #   left_radius: 0.3

  left_wrist:
    # left_wrist_init_rot: [[0.0271625, 0.98434128, -0.17416784],
    #                   [0.21340671, 0.16450532, 0.9630138],
    #                   [0.97658577, -0.06332645, -0.20559666]]
    left_wrist_init_rot: [[ 0,  0, -1], [ 1,  0,  0], [ 0,  -1,  0]]
    left_wrist_init_pos: [-0.314, 0.306, 0.24]
    left_center: [-0.314, 0.306, 0.24]
    # left_wrist_init_pos: [0, -0.4, 0.3]
    # left_center: [0, 0.4, 0.3]
    left_radius: 0.3

  left_agent:
    dynamixel_cfg:
      # port: /dev/serial/by-id/usb-FTDI_USB__-__Serial_Converter_FT8J0QI3-if00-port0
      port: /dev/serial/by-id/usb-FTDI_USB__-__Serial_Converter_FT9HDF53-if00-port0
      urdf: left_arm/robot.urdf
      ee_link_name: ee_c
    hand_cfg:
      cam_num: 4
      hand_type: Left